apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: argocd
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: test
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 30m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
